services:
  api: 
    build: .
    container_name: api
    ports:
      - ${PORT}:${PORT}
    restart: always
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - is-ls

networks:
  is-ls:
    driver: bridge